### ISSUE TITLE
aioftp server does not support "LIST -a"

### ISSUE THREAD

**Issue by fpemud** [aio-libs/aioftp#121]
Sorry to bother you again.

Today I used gnome nautilus (it uses gvfs underneath) as ftp client, but it didn't work.
aioftp server reports "451 file system error" when it receives "LIST -a" from the client. The reason is that aioftp server treats the command argument "-a" as a file.

log1:
```
new connection from 192.168.1.27:59066
220 welcome
FEAT
502 'feat' not implemented
USER
230 anonymous login
FEAT
502 'feat' not implemented
TYPE I
200 
SYST
215 UNIX Type: L8
SITE HELP
502 'site' not implemented
PWD
257 "/"
CWD /
250 
PASV
227-listen socket created
227 (0,0,0,0,152,195)
PORT 192,168,1,27,172,187
502 'port' not implemented
EPSV
229 listen socket already exists (|||39107|)
LIST -a
451 file system error
```

log2, I modified aioftp code so that I can get the detailed exception:
```
Jul 23 22:06:31 fpemud-workstation mirrors[479309]: aioftp.errors.PathIOError
Jul 23 22:06:31 fpemud-workstation mirrors[479309]:     raise aioftp.errors.PathIOError(reason=sys.exc_info())
Jul 23 22:06:31 fpemud-workstation mirrors[479309]:   File "/usr/lib64/mirrors/mc_server_ftp.py", line 125, in wrapper
Jul 23 22:06:31 fpemud-workstation mirrors[479309]:     if await coro(real_path) == fail:
Jul 23 22:06:31 fpemud-workstation mirrors[479309]:   File "/usr/lib64/python3.6/site-packages/aioftp/server.py", line 649, in wrapper
Jul 23 22:06:31 fpemud-workstation mirrors[479309]:     return await f(cls, connection, rest, *args)
Jul 23 22:06:31 fpemud-workstation mirrors[479309]:   File "/usr/lib64/python3.6/site-packages/aioftp/server.py", line 612, in wrapper
Jul 23 22:06:31 fpemud-workstation mirrors[479309]:     result = task.result()
Jul 23 22:06:31 fpemud-workstation mirrors[479309]:   File "/usr/lib64/python3.6/site-packages/aioftp/server.py", line 913, in dispatcher
Jul 23 22:06:31 fpemud-workstation mirrors[479309]: Traceback (most recent call last):
Jul 23 22:06:31 fpemud-workstation mirrors[479309]: During handling of the above exception, another exception occurred:
Jul 23 22:06:31 fpemud-workstation mirrors[479309]: FileNotFoundError: No such file or directory: '-a'
Jul 23 22:06:31 fpemud-workstation mirrors[479309]:     raise FileNotFoundError("No such file or directory: '%s'" % (s))
Jul 23 22:06:31 fpemud-workstation mirrors[479309]:   File "/usr/lib64/mirrors/mc_server_ftp.py", line 249, in _convertPath
Jul 23 22:06:31 fpemud-workstation mirrors[479309]:     path = self._convertPath(path)
Jul 23 22:06:31 fpemud-workstation mirrors[479309]:   File "/usr/lib64/mirrors/mc_server_ftp.py", line 153, in exists
Jul 23 22:06:31 fpemud-workstation mirrors[479309]:     return await coro(*args, **kwargs)
Jul 23 22:06:31 fpemud-workstation mirrors[479309]:   File "/usr/lib64/mirrors/mc_server_ftp.py", line 121, in wrapper
Jul 23 22:06:31 fpemud-workstation mirrors[479309]: Traceback (most recent call last):
```

**Comment by pohmelie** [comment]
As [rfc959](https://tools.ietf.org/html/rfc959) said:
```
LIST (LIST)

            This command causes a list to be sent from the server to the
            passive DTP.  If the pathname specifies a directory or other
            group of files, the server should transfer a list of files
            in the specified directory.  If the pathname specifies a
            file then the server should send current information on the
            file.  A null argument implies the user's current working or
            default directory.  The data transfer is over the data
            connection in type ASCII or type EBCDIC.  (The user must
            ensure that the TYPE is appropriately ASCII or EBCDIC).
            Since the information on a file may vary widely from system
            to system, this information may be hard to use automatically
            in a program, but may be quite useful to a human user.
```
The only argument can be a path.
