### ISSUE TITLE
Tests fail with siosocks 0.2.0

### ISSUE THREAD

**Issue by AMDmi3** [aio-libs/aioftp#127]
Some tests fail with latest siosocks 0.2.0 (but pass with siosocks 0.1.0; siosocks own tests also pass). Maybe because of exception related changes in latest siosocks: https://github.com/pohmelie/siosocks/blob/master/history.md#020-2020-09-01

```pytest
=================================== FAILURES ===================================
______________________ test_socks_fail[127.0.0.1-socks0] _______________________

pair_factory = <class 'conftest.pair_factory.<locals>.Factory'>
Client = <class 'conftest.Container'>
socks = Socks(host='127.0.0.1', port=56318, server=<Server sockets=(<asyncio.TransportSocket fd=16, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 56318)>,)>)

    @pytest.mark.asyncio
    async def test_socks_fail(pair_factory, Client, socks):
        client = Client(socks_host=socks.host, socks_port=socks.port,
                        socks_version=5, username="bar", password="bar")
        with pytest.raises(ValueError):
>           async with pair_factory(client):

tests/test_client_side_socks.py:17: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/conftest.py:121: in __aenter__
    await self.client.connect(self.server.server_host,
aioftp/client.py:604: in connect
    await super().connect(host, port)
aioftp/client.py:131: in connect
    reader, writer = await self._open_connection(host, port)
/usr/local/lib/python3.8/site-packages/siosocks/io/asyncio.py:105: in open_connection
    await async_engine(protocol, io)
/usr/local/lib/python3.8/site-packages/siosocks/interface.py:37: in async_engine
    message = generator_method(data)
/usr/local/lib/python3.8/site-packages/siosocks/protocol.py:281: in SocksClient
    yield from Socks5Client(io).run(host, port, username, password, **socks5_extras)
/usr/local/lib/python3.8/site-packages/siosocks/protocol.py:245: in run
    yield from self.auth(username, password)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <siosocks.protocol.Socks5Client object at 0x803d16d30>, username = 'bar'
password = 'bar'

    def auth(self, username, password):
        auth_required = username is not None
        if auth_required:
            auth_method = Socks5AuthMethod.username_password
        else:
            auth_method = Socks5AuthMethod.no_auth
        yield from self.io.write_struct("BB", 1, auth_method)
        version, code = yield from self.io.read_struct("BB")
        self.verify_version(version)
        if code != auth_method:
            raise SocksException(f"Auth method {_hex(auth_method)} not accepted with {_hex(code)} code")
        if auth_method == Socks5AuthMethod.username_password:
            yield from self.io.write_struct("B", 1)
            yield from self.io.write_pascal_string(username)
            yield from self.io.write_pascal_string(password)
            auth_version, code = yield from self.io.read_struct("BB")
            if auth_version != 1:
                raise SocksException(f"Username/password auth version {_hex(auth_version)} not supported")
            if code != 0:
>               raise SocksException(f"Username/password auth failed with code {_hex(code)}")
E               siosocks.exceptions.SocksException: Username/password auth failed with code 0x01

/usr/local/lib/python3.8/site-packages/siosocks/protocol.py:241: SocksException
------------------------------ Captured log call -------------------------------
ERROR    asyncio:base_events.py:1707 Task exception was never retrieved
future: <Task finished name='Task-356' coro=<socks_server_handler() done, defined at /usr/local/lib/python3.8/site-packages/siosocks/io/asyncio.py:63> exception=SocksException('Wrong username or password')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/siosocks/io/asyncio.py", line 66, in socks_server_handler
    await async_engine(SocksServer(**kwargs), io)
  File "/usr/local/lib/python3.8/site-packages/siosocks/interface.py", line 37, in async_engine
    message = generator_method(data)
  File "/usr/local/lib/python3.8/site-packages/siosocks/protocol.py", line 267, in SocksServer
    yield from Socks5Server(io).run(username, password)
  File "/usr/local/lib/python3.8/site-packages/siosocks/protocol.py", line 205, in run
    yield from self.auth(username, password)
  File "/usr/local/lib/python3.8/site-packages/siosocks/protocol.py", line 200, in auth
    raise SocksException("Wrong username or password")
siosocks.exceptions.SocksException: Wrong username or password
______________________ test_socks_fail[127.0.0.1-socks1] _______________________

pair_factory = <class 'conftest.pair_factory.<locals>.Factory'>
Client = <class 'conftest.Container'>
socks = Socks(host='::1', port=56321, server=<Server sockets=(<asyncio.TransportSocket fd=16, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 56321, 0, 0)>,)>)

    @pytest.mark.asyncio
    async def test_socks_fail(pair_factory, Client, socks):
        client = Client(socks_host=socks.host, socks_port=socks.port,
                        socks_version=5, username="bar", password="bar")
        with pytest.raises(ValueError):
>           async with pair_factory(client):

tests/test_client_side_socks.py:17: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/conftest.py:121: in __aenter__
    await self.client.connect(self.server.server_host,
aioftp/client.py:604: in connect
    await super().connect(host, port)
aioftp/client.py:131: in connect
    reader, writer = await self._open_connection(host, port)
/usr/local/lib/python3.8/site-packages/siosocks/io/asyncio.py:105: in open_connection
    await async_engine(protocol, io)
/usr/local/lib/python3.8/site-packages/siosocks/interface.py:37: in async_engine
    message = generator_method(data)
/usr/local/lib/python3.8/site-packages/siosocks/protocol.py:281: in SocksClient
    yield from Socks5Client(io).run(host, port, username, password, **socks5_extras)
/usr/local/lib/python3.8/site-packages/siosocks/protocol.py:245: in run
    yield from self.auth(username, password)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <siosocks.protocol.Socks5Client object at 0x803dd9040>, username = 'bar'
password = 'bar'

    def auth(self, username, password):
        auth_required = username is not None
        if auth_required:
            auth_method = Socks5AuthMethod.username_password
        else:
            auth_method = Socks5AuthMethod.no_auth
        yield from self.io.write_struct("BB", 1, auth_method)
        version, code = yield from self.io.read_struct("BB")
        self.verify_version(version)
        if code != auth_method:
            raise SocksException(f"Auth method {_hex(auth_method)} not accepted with {_hex(code)} code")
        if auth_method == Socks5AuthMethod.username_password:
            yield from self.io.write_struct("B", 1)
            yield from self.io.write_pascal_string(username)
            yield from self.io.write_pascal_string(password)
            auth_version, code = yield from self.io.read_struct("BB")
            if auth_version != 1:
                raise SocksException(f"Username/password auth version {_hex(auth_version)} not supported")
            if code != 0:
>               raise SocksException(f"Username/password auth failed with code {_hex(code)}")
E               siosocks.exceptions.SocksException: Username/password auth failed with code 0x01

/usr/local/lib/python3.8/site-packages/siosocks/protocol.py:241: SocksException
------------------------------ Captured log call -------------------------------
ERROR    asyncio:base_events.py:1707 Task exception was never retrieved
future: <Task finished name='Task-363' coro=<socks_server_handler() done, defined at /usr/local/lib/python3.8/site-packages/siosocks/io/asyncio.py:63> exception=SocksException('Wrong username or password')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/siosocks/io/asyncio.py", line 66, in socks_server_handler
    await async_engine(SocksServer(**kwargs), io)
  File "/usr/local/lib/python3.8/site-packages/siosocks/interface.py", line 37, in async_engine
    message = generator_method(data)
  File "/usr/local/lib/python3.8/site-packages/siosocks/protocol.py", line 267, in SocksServer
    yield from Socks5Server(io).run(username, password)
  File "/usr/local/lib/python3.8/site-packages/siosocks/protocol.py", line 205, in run
    yield from self.auth(username, password)
  File "/usr/local/lib/python3.8/site-packages/siosocks/protocol.py", line 200, in auth
    raise SocksException("Wrong username or password")
siosocks.exceptions.SocksException: Wrong username or password
_________________________ test_socks_fail[::1-socks0] __________________________

pair_factory = <class 'conftest.pair_factory.<locals>.Factory'>
Client = <class 'conftest.Container'>
socks = Socks(host='127.0.0.1', port=56324, server=<Server sockets=(<asyncio.TransportSocket fd=16, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 56324)>,)>)

    @pytest.mark.asyncio
    async def test_socks_fail(pair_factory, Client, socks):
        client = Client(socks_host=socks.host, socks_port=socks.port,
                        socks_version=5, username="bar", password="bar")
        with pytest.raises(ValueError):
>           async with pair_factory(client):

tests/test_client_side_socks.py:17: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/conftest.py:121: in __aenter__
    await self.client.connect(self.server.server_host,
aioftp/client.py:604: in connect
    await super().connect(host, port)
aioftp/client.py:131: in connect
    reader, writer = await self._open_connection(host, port)
/usr/local/lib/python3.8/site-packages/siosocks/io/asyncio.py:105: in open_connection
    await async_engine(protocol, io)
/usr/local/lib/python3.8/site-packages/siosocks/interface.py:37: in async_engine
    message = generator_method(data)
/usr/local/lib/python3.8/site-packages/siosocks/protocol.py:281: in SocksClient
    yield from Socks5Client(io).run(host, port, username, password, **socks5_extras)
/usr/local/lib/python3.8/site-packages/siosocks/protocol.py:245: in run
    yield from self.auth(username, password)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <siosocks.protocol.Socks5Client object at 0x803e22850>, username = 'bar'
password = 'bar'

    def auth(self, username, password):
        auth_required = username is not None
        if auth_required:
            auth_method = Socks5AuthMethod.username_password
        else:
            auth_method = Socks5AuthMethod.no_auth
        yield from self.io.write_struct("BB", 1, auth_method)
        version, code = yield from self.io.read_struct("BB")
        self.verify_version(version)
        if code != auth_method:
            raise SocksException(f"Auth method {_hex(auth_method)} not accepted with {_hex(code)} code")
        if auth_method == Socks5AuthMethod.username_password:
            yield from self.io.write_struct("B", 1)
            yield from self.io.write_pascal_string(username)
            yield from self.io.write_pascal_string(password)
            auth_version, code = yield from self.io.read_struct("BB")
            if auth_version != 1:
                raise SocksException(f"Username/password auth version {_hex(auth_version)} not supported")
            if code != 0:
>               raise SocksException(f"Username/password auth failed with code {_hex(code)}")
E               siosocks.exceptions.SocksException: Username/password auth failed with code 0x01

/usr/local/lib/python3.8/site-packages/siosocks/protocol.py:241: SocksException
------------------------------ Captured log call -------------------------------
ERROR    asyncio:base_events.py:1707 Task exception was never retrieved
future: <Task finished name='Task-370' coro=<socks_server_handler() done, defined at /usr/local/lib/python3.8/site-packages/siosocks/io/asyncio.py:63> exception=SocksException('Wrong username or password')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/siosocks/io/asyncio.py", line 66, in socks_server_handler
    await async_engine(SocksServer(**kwargs), io)
  File "/usr/local/lib/python3.8/site-packages/siosocks/interface.py", line 37, in async_engine
    message = generator_method(data)
  File "/usr/local/lib/python3.8/site-packages/siosocks/protocol.py", line 267, in SocksServer
    yield from Socks5Server(io).run(username, password)
  File "/usr/local/lib/python3.8/site-packages/siosocks/protocol.py", line 205, in run
    yield from self.auth(username, password)
  File "/usr/local/lib/python3.8/site-packages/siosocks/protocol.py", line 200, in auth
    raise SocksException("Wrong username or password")
siosocks.exceptions.SocksException: Wrong username or password
_________________________ test_socks_fail[::1-socks1] __________________________

pair_factory = <class 'conftest.pair_factory.<locals>.Factory'>
Client = <class 'conftest.Container'>
socks = Socks(host='::1', port=56327, server=<Server sockets=(<asyncio.TransportSocket fd=16, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 56327, 0, 0)>,)>)

    @pytest.mark.asyncio
    async def test_socks_fail(pair_factory, Client, socks):
        client = Client(socks_host=socks.host, socks_port=socks.port,
                        socks_version=5, username="bar", password="bar")
        with pytest.raises(ValueError):
>           async with pair_factory(client):

tests/test_client_side_socks.py:17: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/conftest.py:121: in __aenter__
    await self.client.connect(self.server.server_host,
aioftp/client.py:604: in connect
    await super().connect(host, port)
aioftp/client.py:131: in connect
    reader, writer = await self._open_connection(host, port)
/usr/local/lib/python3.8/site-packages/siosocks/io/asyncio.py:105: in open_connection
    await async_engine(protocol, io)
/usr/local/lib/python3.8/site-packages/siosocks/interface.py:37: in async_engine
    message = generator_method(data)
/usr/local/lib/python3.8/site-packages/siosocks/protocol.py:281: in SocksClient
    yield from Socks5Client(io).run(host, port, username, password, **socks5_extras)
/usr/local/lib/python3.8/site-packages/siosocks/protocol.py:245: in run
    yield from self.auth(username, password)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <siosocks.protocol.Socks5Client object at 0x803971fa0>, username = 'bar'
password = 'bar'

    def auth(self, username, password):
        auth_required = username is not None
        if auth_required:
            auth_method = Socks5AuthMethod.username_password
        else:
            auth_method = Socks5AuthMethod.no_auth
        yield from self.io.write_struct("BB", 1, auth_method)
        version, code = yield from self.io.read_struct("BB")
        self.verify_version(version)
        if code != auth_method:
            raise SocksException(f"Auth method {_hex(auth_method)} not accepted with {_hex(code)} code")
        if auth_method == Socks5AuthMethod.username_password:
            yield from self.io.write_struct("B", 1)
            yield from self.io.write_pascal_string(username)
            yield from self.io.write_pascal_string(password)
            auth_version, code = yield from self.io.read_struct("BB")
            if auth_version != 1:
                raise SocksException(f"Username/password auth version {_hex(auth_version)} not supported")
            if code != 0:
>               raise SocksException(f"Username/password auth failed with code {_hex(code)}")
E               siosocks.exceptions.SocksException: Username/password auth failed with code 0x01

/usr/local/lib/python3.8/site-packages/siosocks/protocol.py:241: SocksException
------------------------------ Captured log call -------------------------------
ERROR    asyncio:base_events.py:1707 Task exception was never retrieved
future: <Task finished name='Task-377' coro=<socks_server_handler() done, defined at /usr/local/lib/python3.8/site-packages/siosocks/io/asyncio.py:63> exception=SocksException('Wrong username or password')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/siosocks/io/asyncio.py", line 66, in socks_server_handler
    await async_engine(SocksServer(**kwargs), io)
  File "/usr/local/lib/python3.8/site-packages/siosocks/interface.py", line 37, in async_engine
    message = generator_method(data)
  File "/usr/local/lib/python3.8/site-packages/siosocks/protocol.py", line 267, in SocksServer
    yield from Socks5Server(io).run(username, password)
  File "/usr/local/lib/python3.8/site-packages/siosocks/protocol.py", line 205, in run
    yield from self.auth(username, password)
  File "/usr/local/lib/python3.8/site-packages/siosocks/protocol.py", line 200, in auth
    raise SocksException("Wrong username or password")
siosocks.exceptions.SocksException: Wrong username or password
==================== 4 failed, 767 passed in 41.15 seconds =====================
```

**Comment by pohmelie** [comment]
Thank you for report :wink:
