### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'resume_reading' in FTPS mode

### ISSUE THREAD

**Issue by PonyPC** [aio-libs/aioftp#138]
Sometimes, there is an AttributeError in FTPS STOR command. If ftp server is behind NAT, it will be much serious.
'''
Traceback (most recent call last):
  File "aioftp/server.py", line 936, in dispatcher
  File "aioftp/server.py", line 464, in wrapper
  File "aioftp/server.py", line 564, in wrapper
  File "aioftp/server.py", line 1305, in stor_worker
  File "aioftp/common.py", line 107, in __anext__
  File "aioftp/common.py", line 509, in read
  File "asyncio/tasks.py", line 494, in wait_for
  File "aioftp/common.py", line 286, in read
  File "asyncio/streams.py", line 690, in read
  File "asyncio/streams.py", line 461, in _maybe_resume_transport
  File "asyncio/sslproto.py", line 344, in resume_reading
AttributeError: 'NoneType' object has no attribute 'resume_reading'
'''
Is it relative to [https://bugs.python.org/issue36098](https://bugs.python.org/issue36098)

**Comment by pohmelie** [comment]
This is python-related bug. More to say, I filled it on bugs.python.org :smile: 
Nothing we can do on `aioftp` side.

**Comment by PonyPC** [comment]
Got it, thanks.
