### ISSUE TITLE
Client.download tries to parse my file's contents

### ISSUE THREAD

**Issue by jmg-duarte** [aio-libs/aioftp#156]
I'm trying to download a `.csv` file off of a server with the following code:
```python
import asyncio
import aioftp

async def main():
    async with aioftp.Client.context(
        # ...
    ) as client:
        await client.download("file.txt")

asyncio.run(main())
```
And I'm getting 
```
ValueError: ('All parsers failed to parse', b'<REDACTED>, [KeyError('1-'), ValueError("time data '11-08-21 09:46PM' does not match format '%m/%d/%Y %I:%M %p'")])
```
However, when I use `download_stream` it works:
```python
import asyncio
import aiofiles
import aioftp

async def main():
    async with aioftp.Client.context(
        # ...
    ) as client:
        async with client.download_stream("file.txt") as stream, aiofiles.open("./test_aio", "wb") as file:
            async for block in stream.iter_by_block():
                await file.write(block)

asyncio.run(main())
``` 

From the error, I have the impression that `aioftp` is trying to parse my file, which it shouldn't do - or at least I don't want it to, I just want to transfer the bytes to my disk...

Am I missing something?

**Comment by pohmelie** [comment]
`download` logic is more complicated. Can you provide full logs for the first case?

**Comment by jmg-duarte** [comment]
Sure, here
```
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:aioftp.client:220 Microsoft FTP Service
DEBUG:aioftp.client:USER <username>
DEBUG:aioftp.client:331 Password required
DEBUG:aioftp.client:PASS ********************
DEBUG:aioftp.client:230 User logged in.
DEBUG:aioftp.client:MLST file.txt
DEBUG:aioftp.client:500 Command not understood.
DEBUG:aioftp.client:TYPE I
DEBUG:aioftp.client:200 Type set to I.
DEBUG:aioftp.client:EPSV
DEBUG:aioftp.client:229 Entering Extended Passive Mode (|||50864|)
DEBUG:aioftp.client:MLSD .
DEBUG:aioftp.client:500 Command not understood.
DEBUG:aioftp.client:TYPE I
DEBUG:aioftp.client:200 Type set to I.
DEBUG:aioftp.client:EPSV
DEBUG:aioftp.client:229 Entering Extended Passive Mode (|||50877|)
DEBUG:aioftp.client:LIST .
DEBUG:aioftp.client:125 Data connection already open; Transfer starting.
DEBUG:aioftp.client:QUIT
DEBUG:aioftp.client:226 Transfer complete.
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    asyncio.run(main())
  File "/Users/duarte/.pyenv/versions/3.8.9/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/duarte/.pyenv/versions/3.8.9/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "test.py", line 17, in main
    await client.download(
  File "/Users/duarte/Documents/data/pdbt/.venv/lib/python3.8/site-packages/aioftp/client.py", line 1061, in download
    if await self.is_file(source):
  File "/Users/duarte/Documents/data/pdbt/.venv/lib/python3.8/site-packages/aioftp/client.py", line 848, in is_file
    info = await self.stat(path)
  File "/Users/duarte/Documents/data/pdbt/.venv/lib/python3.8/site-packages/aioftp/client.py", line 827, in stat
    for p, info in await self.list(path.parent):
  File "/Users/duarte/Documents/data/pdbt/.venv/lib/python3.8/site-packages/aioftp/common.py", line 126, in _to_list
    async for item in self:
  File "/Users/duarte/Documents/data/pdbt/.venv/lib/python3.8/site-packages/aioftp/client.py", line 798, in __anext__
    name, info = cls.parse_line(line)
  File "/Users/duarte/Documents/data/pdbt/.venv/lib/python3.8/site-packages/aioftp/client.py", line 545, in parse_list_line
    raise ValueError("All parsers failed to parse", b, ex)
ValueError: ('All parsers failed to parse', b'04-13-22  01:42PM       <DIR>          DName\r\n', [KeyError('4-'), ValueError("time data '04-13-22 01:42PM' does not match format '%m/%d/%Y %I:%M %p'")])
```

**Comment by pohmelie** [comment]
The problem is that server do not support MLSx commands family, so `aioftp` backs to `LIST` command, which has no strict format rules and made for humans. And @jw4js windows `LIST` parser fails on this line `b'04-13-22  01:42PM       <DIR>          DName\r\n'`. You can write your own `LIST` parser and pass it as `parse_list_line_custom` argument when creating client. But there is no guarantee that this will not fail again with another server.

**Comment by jmg-duarte** [comment]
Oh I see, hence the stream working. I guess I can close since I have a workaround then, though, should this behavior be documented?

**Comment by pohmelie** [comment]
It is actually documented in FTP rfc AFAIR. `LIST` output is not standardized, so `aioftp` can't do proper parsing in all cases/servers implementations.

**Comment by jmg-duarte** [comment]
As a library user, I shouldn't really need to know the FTP spec, so my suggestion is to document the behavior. Even if just to avoid more people creating issues like mine. Either way, it's up to you!

I'll be closing the issue now. Thank you for all the help!

**Comment by pohmelie** [comment]
Agreed. I will add some warning message on `LIST` command to the readme file.
