### ISSUE TITLE
RuntimeError: readuntil() called while another coroutine is already waiting for incoming data

### ISSUE THREAD

**Issue by Modelmat** [aio-libs/aioftp#75]
Here's MWE:
```py
import asyncio
import aioftp
client = aioftp.Client()
async def main():
    await client.connect("ftp.bom.gov.au", 21) # doesn't matter here
    await client.login()
    await asyncio.wait([client.download("google98f6c7a1f42b62d2.html") for _ in range(10)])

asyncio.get_event_loop().run_until_complete(main())
```
Here's the full traceback:
```py
Traceback (most recent call last):
  File "D:\Program Files\Python3\lib\site-packages\aioftp\client.py", line 921, in download
    if await self.is_file(source):
  File "D:\Program Files\Python3\lib\site-packages\aioftp\client.py", line 708, in is_file
    info = await self.stat(path)
  File "D:\Program Files\Python3\lib\site-packages\aioftp\client.py", line 680, in stat
    code, info = await self.command("MLST " + str(path), "2xx")
  File "D:\Program Files\Python3\lib\site-packages\aioftp\client.py", line 244, in command
    code, info = await self.parse_response()
  File "D:\Program Files\Python3\lib\site-packages\aioftp\client.py", line 184, in parse_response
    code, rest = await self.parse_line()
  File "D:\Program Files\Python3\lib\site-packages\aioftp\client.py", line 164, in parse_line
    line = await self.stream.readline()
  File "D:\Program Files\Python3\lib\site-packages\aioftp\common.py", line 537, in readline
    data = await super().readline()
  File "D:\Program Files\Python3\lib\asyncio\tasks.py", line 339, in wait_for
    return (yield from fut)
  File "D:\Program Files\Python3\lib\site-packages\aioftp\common.py", line 275, in readline
    return await self.reader.readline()
  File "D:\Program Files\Python3\lib\asyncio\streams.py", line 488, in readline
    line = yield from self.readuntil(sep)
  File "D:\Program Files\Python3\lib\asyncio\streams.py", line 581, in readuntil
    yield from self._wait_for_data('readuntil')
  File "D:\Program Files\Python3\lib\asyncio\streams.py", line 452, in _wait_for_data
    'already waiting for incoming data' % func_name)
RuntimeError: readuntil() called while another coroutine is already waiting for incoming data
```
From what I can see, this doesn't wait for the current connection to complete while running, and I would rather not create multiple clientsessions which are thrown away.

**Comment by pohmelie** [comment]
FTP protocol do not support concurrent download/upload, if you want real
concurrency you need multiple client sessions. Actually, you do not need
concurrency here, because you have net or disk limit, which will throttle
your concurrency.

**Comment by Modelmat** [comment]
That's what I thought.

What the issue is is that I would think this library should implement some sort of waiting for the current one to finish, through an `asyncio.Lock` or some sort.
________________________________

**Comment by pohmelie** [comment]
No need to lock, library should not encourage abnormal usage. `aioftp` is made not for concurrent downloading, but for `asyncio` apps, which need no extra threads for io. You have two ways: use your code sequential or use multiple client sessions.
