### ISSUE TITLE
downloading multiple files raises StatusCodeError

### ISSUE THREAD

**Issue by toonknapen** [aio-libs/aioftp#83]
When trying to download multiple files from a directory I get an StatutCodeError exception when the second file is trying to download.
I can get rid of it by reconnecting after every download but that can not be the intention
I experienced this on windows10 but also on ubuntu16.04 with vsftpd.

```
import aioftp
import asyncio
import logging
import sys

logging.basicConfig(
                format='%(asctime)s - %(name)s - %(levelname)6s - %(process)d:%(thread)d - %(filename)s:%(lineno)d - %(message)s',
                handlers=[logging.StreamHandler(sys.stdout)],
                level=logging.DEBUG)

async def download(client, file):
    #client.close()
    #await client.connect("localhost")
    #await client.login('ftp', 'me@mine.org')
    #await client.change_directory('XML Feed 2018/Blancpain GT Series Round 1 Sprint Cup/Blancpain GT Series Sprint Cup/Race 1/ChangesArchive')
    st = await client.download_stream(file)
    buffer = await st.read()
    print(buffer)

async def foo():
    client = aioftp.Client()
    await client.connect("localhost")
    await client.login('ftp', 'me@mine.org')
    await client.change_directory('dir_containing_many_files')
    dir = await client.list(raw_command="NLST")

    for i in dir:
        await download(client, str(i[0]))


task = asyncio.ensure_future(foo())
loop = asyncio.get_event_loop()
loop.run_until_complete(task)
```

Below is what the log looks like on ubuntu:

```
2018-10-16 17:36:57,154 - asyncio -  DEBUG - 1138:140043991197440 - selector_events.py:65 - Using selector: EpollSelector
2018-10-16 17:36:57,163 - aioftp.client -   INFO - 1138:140043991197440 - client.py:173 - 220 (vsFTPd 3.0.3)
2018-10-16 17:36:57,164 - aioftp.client -   INFO - 1138:140043991197440 - client.py:173 - 331 Please specify the password.
2018-10-16 17:36:57,195 - aioftp.client -   INFO - 1138:140043991197440 - client.py:173 - 230 Login successful.
2018-10-16 17:36:57,196 - aioftp.client -   INFO - 1138:140043991197440 - client.py:173 - 250 Directory successfully changed.
2018-10-16 17:36:57,197 - aioftp.client -   INFO - 1138:140043991197440 - client.py:173 - 200 Switching to Binary mode.
2018-10-16 17:36:57,198 - aioftp.client -   INFO - 1138:140043991197440 - client.py:173 - 229 Entering Extended Passive Mode (|||44978|)
2018-10-16 17:36:57,202 - aioftp.client -   INFO - 1138:140043991197440 - client.py:173 - 150 Here comes the directory listing.
2018-10-16 17:36:57,233 - aioftp.client -   INFO - 1138:140043991197440 - client.py:173 - 226 Directory send OK.
2018-10-16 17:36:57,233 - aioftp.client -   INFO - 1138:140043991197440 - client.py:173 - 200 Switching to Binary mode.
2018-10-16 17:36:57,234 - aioftp.client -   INFO - 1138:140043991197440 - client.py:173 - 229 Entering Extended Passive Mode (|||40784|)
2018-10-16 17:36:57,237 - aioftp.client -   INFO - 1138:140043991197440 - client.py:173 - 150 Opening BINARY mode data connection for EVENT_LIST_UPDATE_V_1.ZIP (436 bytes).
b"PK\x03\x04\x14\x00\x00\x00\x08\x003u\x87L%\x87./\xd8\x00\x00\x005\x01\x00\x00\x19\x00$\x00EVENT_LIST_UPDATE_V_1.XML\n\x00 \x00\x00\x00\x00\x00\x01\x00\x18\x00\xc5\xce\xf6\xc5m\xce\xd3\x01\xc5\xce\xf6\xc5m\xce\xd3\x01\xc5\xce\xf6\xc5m\xce\xd3\x01\x85\x90=k\xc30\x18\x84\xf7B\xff\x83\xd0\xae/[F\xb6Q\x94%n\tD\xa5\x90\x0c]UUi\x04\xb2\x1clQ\xe5\xe7WiB\xd6n\xc7{\xcf\xf1\x1e'\xd7\x971\x80\x1f7/~\x8a+\xc80\x85k\xf5\xfc$_\xb6\xbb\x01\x14+.\xfde\xf9Z\xc1SJ\xe7\x9e\x90\x9c3\xce5\x9e\xe6oRQ\xca\xc8\x87\xde\xed\xed\xc9\x8d\x06>`\xff?\x8c|\\\x92\x89\xd6\xc1\xf2\n\x00\xa9\xf7\xaf\xc3\x9f*z\xbbQ\xac\xab\x84p\xb5C\x1d\xe3-\xe2\x8d\xf8D\x1d7G\xd4\x1c;QYcyk;I\nx\x8fl\x0e\x8a\nL9\xae(k\x01\xe3=g}]cQ\xb5\x92\x14\xefN\xe9A\xbd\xfb\x14Lt \xfb\x10\xc0tv\x11\x98t\xe5\x9bF\x12\xfdh\xa0\x0f\xeam\x9aG\x13\xca\xf1\x96.\xe2\xd6P\x92\xeb.\xea\x17PK\x01\x02-\x00\x14\x00\x00\x00\x08\x003u\x87L%\x87./\xd8\x00\x00\x005\x01\x00\x00\x19\x00$\x00\x00\x00\x00\x00\x00\x00 \x00\x00\x00\x00\x00\x00\x00EVENT_LIST_UPDATE_V_1.XML\n\x00 \x00\x00\x00\x00\x00\x01\x00\x18\x00\xc5\xce\xf6\xc5m\xce\xd3\x01\xc5\xce\xf6\xc5m\xce\xd3\x01\xc5\xce\xf6\xc5m\xce\xd3\x01PK\x05\x06\x00\x00\x00\x00\x01\x00\x01\x00k\x00\x00\x003\x01\x00\x00\x00\x00"
2018-10-16 17:36:57,238 - aioftp.client -   INFO - 1138:140043991197440 - client.py:173 - 226 Transfer complete.
Traceback (most recent call last):
  File "mytest.py", line 33, in <module>
    loop.run_until_complete(task)
  File "/root/python3.6.5/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "mytest.py", line 28, in foo
    await download(client, str(i[0]))
  File "mytest.py", line 16, in download
    st = await client.download_stream(file)
  File "/home/tknapen/projects/aioftp/venv/lib/python3.6/site-packages/aioftp-0.12.0-py3.6.egg/aioftp/client.py", line 1053, in get_stream
  File "/home/tknapen/projects/aioftp/venv/lib/python3.6/site-packages/aioftp-0.12.0-py3.6.egg/aioftp/client.py", line 1016, in get_passive_connection
  File "/home/tknapen/projects/aioftp/venv/lib/python3.6/site-packages/aioftp-0.12.0-py3.6.egg/aioftp/client.py", line 251, in command
  File "/home/tknapen/projects/aioftp/venv/lib/python3.6/site-packages/aioftp-0.12.0-py3.6.egg/aioftp/client.py", line 218, in check_codes
aioftp.errors.StatusCodeError: Waiting for ('200',) but got 226 [' Transfer complete.']
```

**Comment by pohmelie** [comment]
You use low-level streams, and missed some finalization. https://aioftp.readthedocs.io/client_tutorial.html#advanced-download-and-upload-abort-restart

**Comment by toonknapen** [comment]
thanks, I missed that.
Looking back at it, I see that in https://aioftp.readthedocs.io/client_api.html ```download_stream``` is said to return an ```aioftp.ThrottleStreamIO```. The only class however to have the ```finish()``` method AFAICS is https://aioftp.readthedocs.io/client_api.html#aioftp.DataConnectionThrottleStreamIO which is a sub-class of ThrottleStreamIO.

**Comment by pohmelie** [comment]
Yes, this is documentation bug, I will fix this later. More to say, as documentation said it is better to use context managers.

**Comment by jferencik** [comment]
I have a somehow similar problem. I am downloading many files from a server located in Australia (I am in Central Europe).

I am being a bit resilient and using more than one attempt to fetch the files. My workflow is as follows:
 I detect new files on the server
i split the files  equally if possible  ( i use 2-3 connections)


thi is the functin that creates a client

    async def download_files(self, files_url=None,  no_attempts=3):
        results = list()
        try:
            #todo: upgrade when upgrading aioftp

            # async with aioftp.Client.context(host=self.server_endpoint_url, user=self.ftp_user,
            #                                  password=self.ftp_passwd, account=self.ftp_account,
            #                                  socket_timeout=self.connection_timeout) as ftp_client:
            async with aioftp.ClientSession(host=self.server_endpoint_url, user=self.ftp_user,
                                             password=self.ftp_passwd, account=self.ftp_account,
                                             socket_timeout=self.connection_timeout) as ftp_client:
                self.logger.debug(f'Starting a new client ( {self.server_endpoint_url}) to download'
                                  f' {len(files_url)} file(s) ')
                for furl in files_url:
                    parse_res = urllib.parse.urlparse(furl)
                    path, _ = os.path.split(parse_res.path)
                    try:
                        await ftp_client.change_directory(path)
                    except Exception as ee:
                        _, file_name = os.path.split(furl)
                        local_file_path = self.compose_local_file_path(fname=file_name)
                        results.append((local_file_path, ee))
                        continue

                    try:
                        async with async_timeout.timeout(self.data_read_timeout) as atmc:
                            r = await self.download_file(file_url=furl, no_attempts=no_attempts, ftp_client=ftp_client)
                            results.append(r)
                    except asyncio.TimeoutError as tout:
                        _, file_name = os.path.split(furl)
                        local_file_path = self.compose_local_file_path(fname=file_name)
                        results.append((local_file_path, tout))


        except Exception as e:
            for furl in files_url:
                _, file_name = os.path.split(furl)
                local_file_path = self.compose_local_file_path(fname=file_name)
                results.append((local_file_path, e))

            #results.append((f'Error openning a new FTP connection to {self.server_endpoint_url}', e))

        return results


and this is the download_file function

            for attempt in range(no_attempts):
                    self.logger.info(f'Downloading file {file_name}')
                    try:
                        async with lock.SocketLock(lock_name=lock_name, timeout=3) as socket_lock:
                            #start_stats = await ftp_client.stat(file_name)
                            async with ftp_client.download_stream(file_name, offset=offs) as dstream:
                                async with aiofiles.open(temp_file_path, mode='ab', ) as local_file:
                                    async for data_chunk in dstream.iter_by_block(self.DEFAULT_READ_BLOCK_SIZE):
                                        offs += len(data_chunk)
                                        await  local_file.write(data_chunk)
                                   await stream.finish()
                            #end_stats = await ftp_client.stat(file_name)
                            os.rename(temp_file_path, local_file_path)
                            size = os.path.getsize(local_file_path)
                            if size == 0:
                                raise Exception(f'The downloaded file is empty!')
                            # assert end_stats['size'] == start_stats[
                            #     'size'], f'{file_name} was not downloaded correctly!' \
                            #              f'start_size={start_stats["size"]} != {end_stats["size"]})'

                            rec = await self.create_record(downloaded_file_path=local_file_path, source=source, size=size)
                            await self.record_to_db([rec])
                            self.logger.info(f'File {local_file_path} was successfully downloaded from {source}')
                            return local_file_path, source, size

                    except (lock.LockIOException, asyncio.CancelledError) as ce:
                        if path_exists(temp_file_path):
                            os.remove(temp_file_path)
                        if path_exists(local_file_path):
                            os.remove(local_file_path)
                        return local_file_path, ce

                    except aioftp.StatusCodeError as ftp_e:
                        #no logging here as 550 is INFO not real ERROR
                        if int(ftp_e.received_codes[0]) ==  550:
                            self.logger.debug(f'{file_name} does not exist on the server!')
                            #IGNORE this error
                            # Some FTP downloaders fetch_urls functions DO generate the file names
                            # As such it is entirely possible  the files does not exist yet on the
                            # server. It is a small price to pay for the fact that we do not list the FTP
                            # IN case of BOM for example this is better that constantly
                            # listing the server
                            if path_exists(temp_file_path):
                                os.remove(temp_file_path)
                            if path_exists(local_file_path):
                                os.remove(local_file_path)
                            return None

                        self.logger.error(f' {ftp_e.__class__.__name__} exception encountered: {ftp_e}')

                        if int(ftp_e.received_codes[0]) == 502:
                            #do not try again...just set attempt to max value and the code below will handle it
                            attempt = no_attempts - 1
                        if attempt == no_attempts - 1:
                            if path_exists(temp_file_path):
                                os.remove(temp_file_path)
                            if path_exists(local_file_path):
                                os.remove(local_file_path)
                            self.logger.error(f'Failed to download {file_url} from {source}.')
                            return local_file_path, ftp_e
                            #raise ftp_e
                        self.logger.info('Trying again ...')
                        continue


                    except Exception as exc:

                        self.logger.error(f' {exc.__class__.__name__} exception encountered: {exc}')

                        if attempt == no_attempts - 1:
                            if path_exists(temp_file_path):
                                os.remove(temp_file_path)
                            if path_exists(local_file_path):
                                os.remove(local_file_path)
                            self.logger.error(f'Failed to download {file_url} from {source}.')
                            return local_file_path, exc

                        self.logger.info('Trying again ...')


                        continue

this fucntions are launced from cron repeatedly one after another and results are collected using asyncio.wait and timeout


The log file shows

2021-04-20 20:25:53-H08_ABOM_Downloader_reg_20210420201602-ERROR: StatusCodeError exception encountered: Waiting for ('229',) but got 200 [' Switching to Binary mode.']
2021-04-20 20:25:53-H08_ABOM_Downloader_reg_20210420201602-INFO:Trying again ...
2021-04-20 20:25:53-H08_ABOM_Downloader_reg_20210420201602-INFO:Downloading file IDE00214.202104201720.nc
2021-04-20 20:25:53-H08_ABOM_Downloader_reg_20210420201602-ERROR: StatusCodeError exception encountered: Waiting for ('200',) but got 229 [' Entering Extended Passive Mode (|||15834|).']
2021-04-20 20:25:54-H08_ABOM_Downloader_reg_20210420201602-ERROR:Failed to download ftp://ftp-reg.cloud.bom.gov.au/register/bom560/gms/IDE00214.202104201720.nc from ftp-reg.cloud.bom.gov.au.
2021-04-20 20:25:54-H08_ABOM_Downloader_reg_20210420201602-INFO:Downloading file IDE00214.202104201730.nc
2021-04-20 20:25:54-H08_ABOM_Downloader_reg_20210420201602-ERROR: StatusCodeError exception encountered: Waiting for ('200',) but got 250 [' Directory successfully changed.']
2021-04-20 20:25:54-H08_ABOM_Downloader_reg_20210420201602-INFO:Trying again ...
2021-04-20 20:25:54-H08_ABOM_Downloader_reg_20210420201602-INFO:Downloading file IDE00214.202104201730.nc
2021-04-20 20:25:54-H08_ABOM_Downloader_reg_20210420201602-ERROR: StatusCodeError exception encountered: Waiting for ('229',) but got 200 [' Switching to Binary mode.']
2021-04-20 20:25:54-H08_ABOM_Downloader_reg_20210420201602-INFO:Trying again ...
2021-04-20 20:25:54-H08_ABOM_Downloader_reg_20210420201602-INFO:Downloading file IDE00214.202104201730.nc
2021-04-20 20:25:54-H08_ABOM_Downloader_reg_20210420201602-ERROR: StatusCodeError exception encountered: Waiting for ('200',) but got 229 [' Entering Extended Passive Mode (|||18475|).']
2021-04-20 20:25:54-H08_ABOM_Downloader_reg_20210420201602-ERROR:Failed to download ftp://ftp-reg.cloud.bom.gov.au/register/bom560/gms/IDE00214.202104201730.nc from ftp-reg.cloud.bom.gov.au.
2021-04-20 20:25:55-H08_ABOM_Downloader_reg_20210420201602-INFO:Downloading file IDE00214.202104201750.nc
2021-04-20 20:25:55-H08_ABOM_Downloader_reg_20210420201602-ERROR: StatusCodeError exception encountered: Waiting for ('200',) but got 250 [' Directory successfully changed.']
2021-04-20 20:25:55-H08_ABOM_Downloader_reg_20210420201602-INFO:Trying again ...
2021-04-20 20:25:55-H08_ABOM_Downloader_reg_20210420201602-INFO:Downloading file IDE00214.202104201750.nc
2021-04-20 20:25:55-H08_ABOM_Downloader_reg_20210420201602-ERROR: StatusCodeError exception encountered: Waiting for ('229',) but got 200 [' Switching to Binary mode.']
2021-04-20 20:25:55-H08_ABOM_Downloader_reg_20210420201602-INFO:Trying again ...
2021-04-20 20:25:55-H08_ABOM_Downloader_reg_20210420201602-INFO:Downloading file IDE00214.202104201750.nc
2021-04-20 20:25:55-H08_ABOM_Downloader_reg_20210420201602-ERROR: StatusCodeError exception encountered: Waiting for ('200',) but got 229 [' Entering Extended Passive Mode (|||18905|).']
2021-04-20 20:25:55-H08_ABOM_Downloader_reg_20210420201602-ERROR:Failed to download ftp://ftp-reg.cloud.bom.gov.au/register/bom560/gms/IDE00214.202104201750.nc from ftp-reg.cloud.bom.gov.au.



coul anyone give me some advice as to whay I am getting these StatusCodeError errors?

**Comment by pohmelie** [comment]
@jferencik, this needs `DEBUG` level logs.

**Comment by jferencik** [comment]
@pohmelie, thanks so much for replying,

i set a limit on the number of FTP connections (1) and attempts (1) and a short connection timeout for the client (10 secs)

this is the log for the session

2021-04-21 14:16:28-H08_ABOM_Downloader-INFO:No connection dictionary provided. Records will not be written to DB.
2021-04-21 14:16:28-H08_ABOM_Downloader-INFO:14 files were detected and will be evaluated 
2021-04-21 14:16:28-H08_ABOM_Downloader-INFO:Attempting to download 14 files in 900 seconds
2021-04-21 14:16:29-H08_ABOM_Downloader-INFO:Going to download 11 files in 1 connections from ftp.bom.gov.au
2021-04-21 14:16:29-H08_ABOM_Downloader-INFO:Starting to download 11 files in 900 seconds
2021-04-21 14:16:30-aioftp.client-INFO:220-Welcome to the Bureau of Meteorology FTP service.
2021-04-21 14:16:30-aioftp.client-INFO:220-
2021-04-21 14:16:30-aioftp.client-INFO:220-                              Disclaimer
2021-04-21 14:16:30-aioftp.client-INFO:220-
2021-04-21 14:16:30-aioftp.client-INFO:220-You accept all risks and responsibility for losses, damages, costs and
2021-04-21 14:16:30-aioftp.client-INFO:220-other consequences resulting directly or indirectly from using this site and
2021-04-21 14:16:30-aioftp.client-INFO:220-any information or material available from it.
2021-04-21 14:16:30-aioftp.client-INFO:220-
2021-04-21 14:16:30-aioftp.client-INFO:220-To the maximum permitted by law, the Bureau of Meteorology excludes all
2021-04-21 14:16:30-aioftp.client-INFO:220-liability to any person arising directly or indirectly from using this
2021-04-21 14:16:30-aioftp.client-INFO:220-site and any information or material available from it.
2021-04-21 14:16:30-aioftp.client-INFO:220-
2021-04-21 14:16:30-aioftp.client-INFO:220-Always Check the Information
2021-04-21 14:16:30-aioftp.client-INFO:220-
2021-04-21 14:16:30-aioftp.client-INFO:220-Information at this site:
2021-04-21 14:16:30-aioftp.client-INFO:220-
2021-04-21 14:16:30-aioftp.client-INFO:220-. is general information provided as part of the Bureau of Meteorology's
2021-04-21 14:16:30-aioftp.client-INFO:220-  statutory role in the dissemination of information relating to
2021-04-21 14:16:30-aioftp.client-INFO:220-  meteorology.
2021-04-21 14:16:30-aioftp.client-INFO:220-. is subject to the uncertainties of scientific and technical research
2021-04-21 14:16:30-aioftp.client-INFO:220-. may not be accurate, current or complete
2021-04-21 14:16:30-aioftp.client-INFO:220-. is subject to change without notice
2021-04-21 14:16:30-aioftp.client-INFO:220-. is not a substitute for independent professional advice and users
2021-04-21 14:16:30-aioftp.client-INFO:220-  should obtain any appropriate professional advice relevant to their
2021-04-21 14:16:30-aioftp.client-INFO:220-  particular circumstances
2021-04-21 14:16:30-aioftp.client-INFO:220-. the material on this web site may include the views or recommendations
2021-04-21 14:16:30-aioftp.client-INFO:220-  of third parties, which do not necessarily reflect the views of the
2021-04-21 14:16:30-aioftp.client-INFO:220-  Bureau of Meteorology or indicate its commitment to a particular course of
2021-04-21 14:16:30-aioftp.client-INFO:220-  action.
2021-04-21 14:16:30-aioftp.client-INFO:220
2021-04-21 14:16:30-aioftp.client-INFO:USER 
2021-04-21 14:16:30-aioftp.client-INFO:331 Please specify the password.
2021-04-21 14:16:30-aioftp.client-INFO:PASS 
2021-04-21 14:16:31-aioftp.client-INFO:230 Login successful.
2021-04-21 14:16:31-aioftp.client-INFO:CWD /register/bom560/gms
2021-04-21 14:16:31-aioftp.client-INFO:250 Directory successfully changed.
2021-04-21 14:16:31-H08_ABOM_Downloader-INFO:Downloading file IDE00208.202104211150.nc
2021-04-21 14:16:31-aioftp.client-INFO:TYPE I
2021-04-21 14:16:31-aioftp.client-INFO:200 Switching to Binary mode.
2021-04-21 14:16:31-aioftp.client-INFO:EPSV
2021-04-21 14:16:32-aioftp.client-INFO:229 Entering Extended Passive Mode (|||54092|).
2021-04-21 14:16:32-aioftp.client-INFO:RETR IDE00208.202104211150.nc
2021-04-21 14:16:33-aioftp.client-INFO:150 Opening BINARY mode data connection for IDE00208.202104211150.nc (21174650 bytes).
2021-04-21 14:16:43-H08_ABOM_Downloader-ERROR: TimeoutError exception encountered: 
2021-04-21 14:16:43-H08_ABOM_Downloader-ERROR:Failed to download ftp://ftp.bom.gov.au/register/bom560/gms/IDE00208.202104211150.nc from ftp.bom.gov.au.
2021-04-21 14:16:43-aioftp.client-INFO:CWD /register/bom560/gms
2021-04-21 14:16:53-aioftp.client-INFO:CWD /register/bom560/gms
2021-04-21 14:16:59-aioftp.client-INFO:426 Failure writing network stream.
2021-04-21 14:16:59-aioftp.client-INFO:CWD /register/bom560/gms
2021-04-21 14:16:59-aioftp.client-INFO:250 Directory successfully changed.
2021-04-21 14:16:59-H08_ABOM_Downloader-INFO:Downloading file IDE00208.202104211200.nc
2021-04-21 14:16:59-aioftp.client-INFO:TYPE I
2021-04-21 14:16:59-aioftp.client-INFO:250 Directory successfully changed.
2021-04-21 14:16:59-H08_ABOM_Downloader-ERROR: StatusCodeError exception encountered: Waiting for ('200',) but got 250 [' Directory successfully changed.']
2021-04-21 14:16:59-H08_ABOM_Downloader-ERROR:Failed to download ftp://ftp.bom.gov.au/register/bom560/gms/IDE00208.202104211200.nc from ftp.bom.gov.au.
2021-04-21 14:16:59-aioftp.client-INFO:CWD /register/bom560/gms
2021-04-21 14:16:59-aioftp.client-INFO:250 Directory successfully changed.
2021-04-21 14:16:59-H08_ABOM_Downloader-INFO:Downloading file IDE00208.202104211050.nc
2021-04-21 14:16:59-aioftp.client-INFO:TYPE I
2021-04-21 14:17:00-aioftp.client-INFO:200 Switching to Binary mode.
2021-04-21 14:17:00-aioftp.client-INFO:EPSV
2021-04-21 14:17:00-aioftp.client-INFO:250 Directory successfully changed.
2021-04-21 14:17:00-H08_ABOM_Downloader-ERROR: StatusCodeError exception encountered: Waiting for ('229',) but got 250 [' Directory successfully changed.']
2021-04-21 14:17:00-H08_ABOM_Downloader-ERROR:Failed to download ftp://ftp.bom.gov.au/register/bom560/gms/IDE00208.202104211050.nc from ftp.bom.gov.au.
2021-04-21 14:17:00-aioftp.client-INFO:CWD /register/bom560/gms
2021-04-21 14:17:00-aioftp.client-INFO:200 Switching to Binary mode.
2021-04-21 14:17:00-H08_ABOM_Downloader-INFO:Downloading file IDE00208.202104211000.nc
2021-04-21 14:17:00-aioftp.client-INFO:TYPE I
2021-04-21 14:17:00-aioftp.client-INFO:229 Entering Extended Passive Mode (|||48789|).
2021-04-21 14:17:00-H08_ABOM_Downloader-ERROR: StatusCodeError exception encountered: Waiting for ('200',) but got 229 [' Entering Extended Passive Mode (|||48789|).']
2021-04-21 14:17:00-H08_ABOM_Downloader-ERROR:Failed to download ftp://ftp.bom.gov.au/register/bom560/gms/IDE00208.202104211000.nc from ftp.bom.gov.au.
2021-04-21 14:17:00-aioftp.client-INFO:CWD /register/bom560/gms
2021-04-21 14:17:00-aioftp.client-INFO:250 Directory successfully changed.
2021-04-21 14:17:00-H08_ABOM_Downloader-INFO:Downloading file IDE00208.202104211210.nc
2021-04-21 14:17:00-aioftp.client-INFO:TYPE I
2021-04-21 14:17:00-aioftp.client-INFO:200 Switching to Binary mode.
2021-04-21 14:17:00-aioftp.client-INFO:EPSV
2021-04-21 14:17:01-aioftp.client-INFO:250 Directory successfully changed.
2021-04-21 14:17:01-H08_ABOM_Downloader-ERROR: StatusCodeError exception encountered: Waiting for ('229',) but got 250 [' Directory successfully changed.']
2021-04-21 14:17:01-H08_ABOM_Downloader-ERROR:Failed to download ftp://ftp.bom.gov.au/register/bom560/gms/IDE00208.202104211210.nc from ftp.bom.gov.au.
2021-04-21 14:17:01-aioftp.client-INFO:CWD /register/bom560/gms
2021-04-21 14:17:01-aioftp.client-INFO:200 Switching to Binary mode.
2021-04-21 14:17:01-H08_ABOM_Downloader-INFO:Downloading file IDE00208.202104211140.nc
2021-04-21 14:17:01-aioftp.client-INFO:TYPE I
2021-04-21 14:17:01-aioftp.client-INFO:229 Entering Extended Passive Mode (|||38110|).
2021-04-21 14:17:01-H08_ABOM_Downloader-ERROR: StatusCodeError exception encountered: Waiting for ('200',) but got 229 [' Entering Extended Passive Mode (|||38110|).']
2021-04-21 14:17:01-H08_ABOM_Downloader-ERROR:Failed to download ftp://ftp.bom.gov.au/register/bom560/gms/IDE00208.202104211140.nc from ftp.bom.gov.au.
2021-04-21 14:17:01-aioftp.client-INFO:CWD /register/bom560/gms
2021-04-21 14:17:01-aioftp.client-INFO:250 Directory successfully changed.
2021-04-21 14:17:01-H08_ABOM_Downloader-INFO:Downloading file IDE00208.202104211100.nc
2021-04-21 14:17:01-aioftp.client-INFO:TYPE I
2021-04-21 14:17:01-aioftp.client-INFO:200 Switching to Binary mode.
2021-04-21 14:17:01-aioftp.client-INFO:EPSV
2021-04-21 14:17:02-aioftp.client-INFO:250 Directory successfully changed.
2021-04-21 14:17:02-H08_ABOM_Downloader-ERROR: StatusCodeError exception encountered: Waiting for ('229',) but got 250 [' Directory successfully changed.']
2021-04-21 14:17:02-H08_ABOM_Downloader-ERROR:Failed to download ftp://ftp.bom.gov.au/register/bom560/gms/IDE00208.202104211100.nc from ftp.bom.gov.au.
2021-04-21 14:17:02-aioftp.client-INFO:CWD /register/bom560/gms
2021-04-21 14:17:02-aioftp.client-INFO:200 Switching to Binary mode.
2021-04-21 14:17:02-H08_ABOM_Downloader-INFO:Downloading file IDE00208.202104211030.nc
2021-04-21 14:17:02-aioftp.client-INFO:TYPE I
2021-04-21 14:17:02-aioftp.client-INFO:229 Entering Extended Passive Mode (|||17193|).
2021-04-21 14:17:02-H08_ABOM_Downloader-ERROR: StatusCodeError exception encountered: Waiting for ('200',) but got 229 [' Entering Extended Passive Mode (|||17193|).']
2021-04-21 14:17:02-H08_ABOM_Downloader-ERROR:Failed to download ftp://ftp.bom.gov.au/register/bom560/gms/IDE00208.202104211030.nc from ftp.bom.gov.au.
2021-04-21 14:17:02-aioftp.client-INFO:CWD /register/bom560/gms
2021-04-21 14:17:02-aioftp.client-INFO:250 Directory successfully changed.
2021-04-21 14:17:02-H08_ABOM_Downloader-INFO:Downloading file IDE00208.202104211110.nc
2021-04-21 14:17:02-aioftp.client-INFO:TYPE I
2021-04-21 14:17:03-aioftp.client-INFO:200 Switching to Binary mode.
2021-04-21 14:17:03-aioftp.client-INFO:EPSV
2021-04-21 14:17:03-aioftp.client-INFO:250 Directory successfully changed.
2021-04-21 14:17:03-H08_ABOM_Downloader-ERROR: StatusCodeError exception encountered: Waiting for ('229',) but got 250 [' Directory successfully changed.']
2021-04-21 14:17:03-H08_ABOM_Downloader-ERROR:Failed to download ftp://ftp.bom.gov.au/register/bom560/gms/IDE00208.202104211110.nc from ftp.bom.gov.au.
2021-04-21 14:17:03-aioftp.client-INFO:QUIT
2021-04-21 14:17:03-aioftp.client-INFO:200 Switching to Binary mode.
2021-04-21 14:17:03-H08_ABOM_Downloader-INFO:result is ('/data/satellite_himawari/abom/incoming/IDE00208.202104211150.nc', TimeoutError())
2021-04-21 14:17:03-H08_ABOM_Downloader-INFO:result is ('/data/satellite_himawari/abom/incoming/IDE00208.202104211040.nc', TimeoutError())
2021-04-21 14:17:03-H08_ABOM_Downloader-INFO:result is ('/data/satellite_himawari/abom/incoming/IDE00208.202104211120.nc', StatusCodeError("Waiting for ('2xx',) but got 426 [' Failure writing network stream.']",))
2021-04-21 14:17:03-H08_ABOM_Downloader-INFO:result is ('/data/satellite_himawari/abom/incoming/IDE00208.202104211200.nc', StatusCodeError("Waiting for ('200',) but got 250 [' Directory successfully changed.']",))
2021-04-21 14:17:03-H08_ABOM_Downloader-INFO:result is ('/data/satellite_himawari/abom/incoming/IDE00208.202104211050.nc', StatusCodeError("Waiting for ('229',) but got 250 [' Directory successfully changed.']",))
2021-04-21 14:17:03-H08_ABOM_Downloader-INFO:result is ('/data/satellite_himawari/abom/incoming/IDE00208.202104211000.nc', StatusCodeError("Waiting for ('200',) but got 229 [' Entering Extended Passive Mode (|||48789|).']",))
2021-04-21 14:17:03-H08_ABOM_Downloader-INFO:result is ('/data/satellite_himawari/abom/incoming/IDE00208.202104211210.nc', StatusCodeError("Waiting for ('229',) but got 250 [' Directory successfully changed.']",))
2021-04-21 14:17:03-H08_ABOM_Downloader-INFO:result is ('/data/satellite_himawari/abom/incoming/IDE00208.202104211140.nc', StatusCodeError("Waiting for ('200',) but got 229 [' Entering Extended Passive Mode (|||38110|).']",))
2021-04-21 14:17:03-H08_ABOM_Downloader-INFO:result is ('/data/satellite_himawari/abom/incoming/IDE00208.202104211100.nc', StatusCodeError("Waiting for ('229',) but got 250 [' Directory successfully changed.']",))
2021-04-21 14:17:03-H08_ABOM_Downloader-INFO:result is ('/data/satellite_himawari/abom/incoming/IDE00208.202104211030.nc', StatusCodeError("Waiting for ('200',) but got 229 [' Entering Extended Passive Mode (|||17193|).']",))
2021-04-21 14:17:03-H08_ABOM_Downloader-INFO:result is ('/data/satellite_himawari/abom/incoming/IDE00208.202104211110.nc', StatusCodeError("Waiting for ('229',) but got 250 [' Directory successfully changed.']",))
2021-04-21 14:17:03-H08_ABOM_Downloader-INFO:No files were downloaded.
2021-04-21 14:17:03-H08_ABOM_Downloader-INFO:H08_ABOM_Downloader total run time 0:00:35.102637

I hope you can make some sense of it

**Comment by pohmelie** [comment]
I think I got the problem. FTP is very «sequency» protocol. If order of request/response is missed, then you in trouble. Your log is the example. What is going on here:
- trying to download file
- your timeout (no abort call)
- calling change directory
- no response, your timeout
- calling change directory again
- success response, directory changed
- calling set binary type
- success response, directory changed (and this is not what «set binary type» expect in response)

I can suggest recreate ftp client each time you fail by timeout or something.
